# Site settings
title: mac's/var/log
SEOTitle: /var/log
header-img: img/home-bg.jpg
email: blog@machhral.com
description: "Logs of a curious dev exploring code, self-hosting, and the indie web"
keyword: " mac, blog, developer, self-hosting, raspberry pi, programming, Jekyll"
url: "https://hellybrine.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: hellybrine
twitter_username: huxpro

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true 

plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: mac

# Netease settings
netease_comment: false


# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "A relaxed dev life, one log at a time"
sidebar-avatar: https://github.com/hellybrine.png

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
#friends:
#  [
#    { title: "乱序（Midare）", href: "http://mida.re/" },
#    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#    { title: "Kun Qian", href: "http://kunq.me" },
#    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#    { title: "SmdCn", href: "http://blog.smdcn.net" },
#    { title: "JiyinYiyong", href: "http://tiye.me/" },
#    { title: "DHong Say", href: "http://dhong.co" },
#    { title: "尹峰以为", href: "http://ingf.github.io/" },
#  ]
